### ISSUE TITLE
Simplify installation process

### ISSUE THREAD

**Issue by nydevel** [project-talan/tln-cli#188]
It will be very helpful, if user can install binary from packages (exe installer file in Windows).
Maybe electron will help in this case.

**Comment by VladyslavKurmaz** [comment]
Using platform-specific installation mechanism is something that tln-cli tries to avoid for a couple of reasons:
* exe/msi in most cases will require interaction with UI and this is definitely not CI-friendly approach, tln-cli aims to provide uniform DEV/CI experience.
* exe/msi will modify OS configuration, uninstall process could be non-trivial too
* "installer" almost never allows you no have multiple versions of some component coexisting, this is true for other approaches like - alternatives, brew etc. Solutions like nvm, will require additional manual work every time you need to switch from one version to another.
...
tln-cli vision:
* download requested version of component, usually zip archive or executable.
* put it in predicted location
* construct dev/ci environment in "run-time" via environment variables
* uninstall process is just folder removal operation
